### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by mango7789** [OpenExamFDU/FDU-csdiy#2]
- 关于课程的建议应该包含对老师教学的评价，应对期末考需要学习的知识点，有哪些很重要但课上不会提到的东西（也可以考虑加入课程workload的信息）。这里貌似只是**简单的罗列出一堆学习资料**，也没有说明应该怎么用，对于新手来说可能不是那么友好？
- 文件的名称或许用 课程代码/英文名称 会好一点，拼音感觉有点怪怪的
- 可以考虑加入课程规划图（拓扑图），ds是缺了不少计算机的课的...

**Comment by OpenExamFDU** [comment]
感谢建议。
- 关于第一条，目前旦夕已经有评课社区，自学手册目前只有少数成员维护，不足以覆盖全部授课老师，评价也无法足够客观，教学评价可以参考评课社区结果，课程workload信息也是类似，这里就不重复了。
- 关于第一条补充期末考试知识点等，虽然自学手册不希望主动宣传自学代替上课的思想，但就实际情况看，多数参与成员本科阶段尤其是后期，基本不实地上课，列出的学习资料就是成员贡献的当时代替课程自学所使用的材料。从设计思路看，以课程名划分不同板块主要方便涵盖相关内容。虽然会根据校内大纲适当调整内容，但建议主要服务目标并不是如何取得好成绩，更多只是介绍学好相关内容的可以参考的资源。
- 关于课程规划，我们在Miscellaneous板块添加了北美高校以及国内其他高校的培养方案和路径作为参考。

**Comment by mango7789** [comment]
> 感谢建议。
> 
> * 关于第一条，目前旦夕已经有评课社区，自学手册目前只有少数成员维护，不足以覆盖全部授课老师，评价也无法足够客观，教学评价可以参考评课社区结果，课程workload信息也是类似，这里就不重复了。
> * 关于第一条补充期末考试知识点等，虽然自学手册不希望主动宣传自学代替上课的思想，但就实际情况看，多数参与成员本科阶段尤其是后期，基本不实地上课，列出的学习资料就是成员贡献的当时代替课程自学所使用的材料。从设计思路看，以课程名划分不同板块主要方便涵盖相关内容。虽然会根据校内大纲适当调整内容，但建议主要服务目标并不是如何取得好成绩，更多只是介绍学好相关内容的可以参考的资源。
> * 关于课程规划，我们在Miscellaneous板块添加了北美高校以及国内其他高校的培养方案和路径作为参考。

感谢解答。

- Miscellaneous那个板块放在最后面我还真的没有注意到 :joy:（或许可以把它放在大类基础的前面？），感谢你们的收集与整理。
- 另外一点小的建议是专业选修也可以划分一下不同院系的课。
- 有时间我也写写ds的课提交pr :wink:
